version: "2"
services:
  mydb:
    container_name: "mydb"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /server/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    image: mysql:8.0
  myredis:
    container_name: "myredis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /server/redis:/data
      - /etc/localtime:/etc/localtime:ro
    image: redis:3.2
  myphp:
    container_name: "myphp"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /server/www:/var/www/html
      - /server/php:/usr/local/etc/php
      - /etc/localtime:/etc/localtime:ro
    links:
      - "mydb"
      - "myredis"
    image: php:7.2-fpm
  mynginx:
    container_name: "mynginx"
    restart: always
    ports:
      - "80:80"
    links:
      - "myphp"
    volumes:
      - /server/www:/usr/share/nginx/html
      - /server/nginx:/etc/nginx
      - /server/logs/nginx.logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    command: [nginx-debug, '-g', 'daemon off;']

    image: nginx:latest