version: "2"
services:
  myphp:
    container_name: "myphp"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /server/www:/var/www/html
      - /server/php:/usr/local/etc
      - /etc/localtime:/etc/localtime:ro
    image: php:7.2-fpm
  mynginx:
    container_name: "mynginx"
    restart: always
    ports:
      - "80:80"
    links:
      - "myphp"
    volumes:
      - /server/www:/usr/share/nginx/html
      - /server/nginx:/etc/nginx
      - /server/logs/nginx.logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    command: [nginx-debug, '-g', 'daemon off;']

    image: nginx:latest